### ISSUE TITLE
pcp_systemdb_info command not found

### ISSUE THREAD

**Issue by thiagoTeams** [pgpool/pgpooladmin#4]
<img width="1408" alt="Screen Shot 2021-01-10 at 21 48 44" src="https://user-images.githubusercontent.com/22792533/104126183-c70dda00-538d-11eb-8f3b-5939d3b4355b.png">
Error pcp_systemdb_info command not found
pgpool-II 4.1.0
pgpoolAdmin 4.1.0

**Comment by pengbo0328** [comment]
Thank you for reporting this issue.
It is a bug. I am going to fix this bug.

**Comment by pengbo0328** [comment]
It is fixed.
[commit](https://github.com/pgpool/pgpooladmin/commit/343e126a2266fbe36dcd8d010bd36345ab5c9edb)
